### ISSUE TITLE
If I load Flask, I have this error « No module named werkzeug.exceptions »

### ISSUE THREAD

**Issue by harobed** [tuomasr/pazel#20]
Hi,

in [flask-bug](https://github.com/harobed/pazel/tree/flask-bug) branch, I can execute with success:

```sh
$ bazel build //...
INFO: Invocation ID: 6fe25081-9152-484d-8c1f-2f3d90e9a465
INFO: Analysed 16 targets (0 packages loaded, 0 targets configured).
INFO: Found 16 targets...
INFO: Elapsed time: 0,144s, Critical Path: 0,00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

Next, I have this bug:

```sh
$ bazel run //foo:bar7
INFO: Invocation ID: bb6b6802-087a-4fd1-9fca-00dfa0eaf660
INFO: Analysed target //foo:bar7 (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //foo:bar7 up-to-date:
  bazel-bin/foo/bar7
INFO: Elapsed time: 0,137s, Critical Path: 0,00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_stephane/f33c4e96bb636c7c114d11d080a30ed7/execroot/sample_app/bazel-out/darwin-fastbuild/bin/foo/bar7.runfiles/sample_app/foo/bar7.py", line 1, in <module>
    from flask import Flask
  File "/private/var/tmp/_bazel_stephane/f33c4e96bb636c7c114d11d080a30ed7/execroot/sample_app/bazel-out/darwin-fastbuild/bin/foo/bar7.runfiles/pypi__Flask_1_0_2/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
ImportError: No module named werkzeug.exceptions
```

**Comment by harobed** [comment]
Error come from here https://github.com/bazelbuild/rules_python/blob/1b2621a253744ac607645f2febeb980cdd1293d0/rules_python/whl.py#L110

**Comment by harobed** [comment]
See also https://github.com/bazelbuild/rules_python/pull/90
